// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: entities.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityType int32

const (
	EntityType_ENTITY_TYPE_UNKNOWN    EntityType = 0
	EntityType_ENTITY_TYPE_ASTEROID   EntityType = 1
	EntityType_ENTITY_TYPE_PLAYER     EntityType = 2
	EntityType_ENTITY_TYPE_POWERUP    EntityType = 3
	EntityType_ENTITY_TYPE_PROJECTILE EntityType = 4
	EntityType_ENTITY_TYPE_MOCK       EntityType = 5
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_TYPE_UNKNOWN",
		1: "ENTITY_TYPE_ASTEROID",
		2: "ENTITY_TYPE_PLAYER",
		3: "ENTITY_TYPE_POWERUP",
		4: "ENTITY_TYPE_PROJECTILE",
		5: "ENTITY_TYPE_MOCK",
	}
	EntityType_value = map[string]int32{
		"ENTITY_TYPE_UNKNOWN":    0,
		"ENTITY_TYPE_ASTEROID":   1,
		"ENTITY_TYPE_PLAYER":     2,
		"ENTITY_TYPE_POWERUP":    3,
		"ENTITY_TYPE_PROJECTILE": 4,
		"ENTITY_TYPE_MOCK":       5,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_entities_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_entities_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{0}
}

type EntityData struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Type     EntityType             `protobuf:"varint,1,opt,name=type,proto3,enum=dogfight.EntityType" json:"type,omitempty"`
	Id       string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Position *Vector                `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Velocity *Vector                `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Rotation float64                `protobuf:"fixed64,5,opt,name=rotation,proto3" json:"rotation,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*EntityData_AsteroidData_
	//	*EntityData_PlayerData_
	//	*EntityData_PowerupData_
	//	*EntityData_ProjectileData_
	Data          isEntityData_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityData) Reset() {
	*x = EntityData{}
	mi := &file_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityData) ProtoMessage() {}

func (x *EntityData) ProtoReflect() protoreflect.Message {
	mi := &file_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityData.ProtoReflect.Descriptor instead.
func (*EntityData) Descriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{0}
}

func (x *EntityData) GetType() EntityType {
	if x != nil {
		return x.Type
	}
	return EntityType_ENTITY_TYPE_UNKNOWN
}

func (x *EntityData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityData) GetPosition() *Vector {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EntityData) GetVelocity() *Vector {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *EntityData) GetRotation() float64 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *EntityData) GetData() isEntityData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EntityData) GetAsteroidData() *EntityData_AsteroidData {
	if x != nil {
		if x, ok := x.Data.(*EntityData_AsteroidData_); ok {
			return x.AsteroidData
		}
	}
	return nil
}

func (x *EntityData) GetPlayerData() *EntityData_PlayerData {
	if x != nil {
		if x, ok := x.Data.(*EntityData_PlayerData_); ok {
			return x.PlayerData
		}
	}
	return nil
}

func (x *EntityData) GetPowerupData() *EntityData_PowerupData {
	if x != nil {
		if x, ok := x.Data.(*EntityData_PowerupData_); ok {
			return x.PowerupData
		}
	}
	return nil
}

func (x *EntityData) GetProjectileData() *EntityData_ProjectileData {
	if x != nil {
		if x, ok := x.Data.(*EntityData_ProjectileData_); ok {
			return x.ProjectileData
		}
	}
	return nil
}

type isEntityData_Data interface {
	isEntityData_Data()
}

type EntityData_AsteroidData_ struct {
	AsteroidData *EntityData_AsteroidData `protobuf:"bytes,6,opt,name=asteroidData,proto3,oneof"`
}

type EntityData_PlayerData_ struct {
	PlayerData *EntityData_PlayerData `protobuf:"bytes,7,opt,name=playerData,proto3,oneof"`
}

type EntityData_PowerupData_ struct {
	PowerupData *EntityData_PowerupData `protobuf:"bytes,8,opt,name=powerupData,proto3,oneof"`
}

type EntityData_ProjectileData_ struct {
	ProjectileData *EntityData_ProjectileData `protobuf:"bytes,9,opt,name=projectileData,proto3,oneof"`
}

func (*EntityData_AsteroidData_) isEntityData_Data() {}

func (*EntityData_PlayerData_) isEntityData_Data() {}

func (*EntityData_PowerupData_) isEntityData_Data() {}

func (*EntityData_ProjectileData_) isEntityData_Data() {}

type EntityData_AsteroidData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Vector              `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityData_AsteroidData) Reset() {
	*x = EntityData_AsteroidData{}
	mi := &file_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityData_AsteroidData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityData_AsteroidData) ProtoMessage() {}

func (x *EntityData_AsteroidData) ProtoReflect() protoreflect.Message {
	mi := &file_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityData_AsteroidData.ProtoReflect.Descriptor instead.
func (*EntityData_AsteroidData) Descriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{0, 0}
}

func (x *EntityData_AsteroidData) GetPoints() []*Vector {
	if x != nil {
		return x.Points
	}
	return nil
}

type EntityData_PlayerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Score         uint32                 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Flags         uint32                 `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityData_PlayerData) Reset() {
	*x = EntityData_PlayerData{}
	mi := &file_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityData_PlayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityData_PlayerData) ProtoMessage() {}

func (x *EntityData_PlayerData) ProtoReflect() protoreflect.Message {
	mi := &file_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityData_PlayerData.ProtoReflect.Descriptor instead.
func (*EntityData_PlayerData) Descriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{0, 1}
}

func (x *EntityData_PlayerData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EntityData_PlayerData) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *EntityData_PlayerData) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type EntityData_PowerupData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ability       uint32                 `protobuf:"varint,1,opt,name=ability,proto3" json:"ability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityData_PowerupData) Reset() {
	*x = EntityData_PowerupData{}
	mi := &file_entities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityData_PowerupData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityData_PowerupData) ProtoMessage() {}

func (x *EntityData_PowerupData) ProtoReflect() protoreflect.Message {
	mi := &file_entities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityData_PowerupData.ProtoReflect.Descriptor instead.
func (*EntityData_PowerupData) Descriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{0, 2}
}

func (x *EntityData_PowerupData) GetAbility() uint32 {
	if x != nil {
		return x.Ability
	}
	return 0
}

type EntityData_ProjectileData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         uint32                 `protobuf:"varint,1,opt,name=flags,proto3" json:"flags,omitempty"`
	Lifetime      int32                  `protobuf:"varint,2,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityData_ProjectileData) Reset() {
	*x = EntityData_ProjectileData{}
	mi := &file_entities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityData_ProjectileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityData_ProjectileData) ProtoMessage() {}

func (x *EntityData_ProjectileData) ProtoReflect() protoreflect.Message {
	mi := &file_entities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityData_ProjectileData.ProtoReflect.Descriptor instead.
func (*EntityData_ProjectileData) Descriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{0, 3}
}

func (x *EntityData_ProjectileData) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *EntityData_ProjectileData) GetLifetime() int32 {
	if x != nil {
		return x.Lifetime
	}
	return 0
}

var File_entities_proto protoreflect.FileDescriptor

const file_entities_proto_rawDesc = "" +
	"\n" +
	"\x0eentities.proto\x12\bdogfight\x1a\fvector.proto\"\xe4\x05\n" +
	"\n" +
	"EntityData\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.dogfight.EntityTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12,\n" +
	"\bposition\x18\x03 \x01(\v2\x10.dogfight.VectorR\bposition\x12,\n" +
	"\bvelocity\x18\x04 \x01(\v2\x10.dogfight.VectorR\bvelocity\x12\x1a\n" +
	"\brotation\x18\x05 \x01(\x01R\brotation\x12G\n" +
	"\fasteroidData\x18\x06 \x01(\v2!.dogfight.EntityData.AsteroidDataH\x00R\fasteroidData\x12A\n" +
	"\n" +
	"playerData\x18\a \x01(\v2\x1f.dogfight.EntityData.PlayerDataH\x00R\n" +
	"playerData\x12D\n" +
	"\vpowerupData\x18\b \x01(\v2 .dogfight.EntityData.PowerupDataH\x00R\vpowerupData\x12M\n" +
	"\x0eprojectileData\x18\t \x01(\v2#.dogfight.EntityData.ProjectileDataH\x00R\x0eprojectileData\x1a8\n" +
	"\fAsteroidData\x12(\n" +
	"\x06points\x18\x01 \x03(\v2\x10.dogfight.VectorR\x06points\x1aT\n" +
	"\n" +
	"PlayerData\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05score\x18\x02 \x01(\rR\x05score\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\rR\x05flags\x1a'\n" +
	"\vPowerupData\x12\x18\n" +
	"\aability\x18\x01 \x01(\rR\aability\x1aB\n" +
	"\x0eProjectileData\x12\x14\n" +
	"\x05flags\x18\x01 \x01(\rR\x05flags\x12\x1a\n" +
	"\blifetime\x18\x02 \x01(\x05R\blifetimeB\x06\n" +
	"\x04data*\xa2\x01\n" +
	"\n" +
	"EntityType\x12\x17\n" +
	"\x13ENTITY_TYPE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14ENTITY_TYPE_ASTEROID\x10\x01\x12\x16\n" +
	"\x12ENTITY_TYPE_PLAYER\x10\x02\x12\x17\n" +
	"\x13ENTITY_TYPE_POWERUP\x10\x03\x12\x1a\n" +
	"\x16ENTITY_TYPE_PROJECTILE\x10\x04\x12\x14\n" +
	"\x10ENTITY_TYPE_MOCK\x10\x05B\x05Z\x03/pbb\x06proto3"

var (
	file_entities_proto_rawDescOnce sync.Once
	file_entities_proto_rawDescData []byte
)

func file_entities_proto_rawDescGZIP() []byte {
	file_entities_proto_rawDescOnce.Do(func() {
		file_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_proto_rawDesc), len(file_entities_proto_rawDesc)))
	})
	return file_entities_proto_rawDescData
}

var file_entities_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_entities_proto_goTypes = []any{
	(EntityType)(0),                   // 0: dogfight.EntityType
	(*EntityData)(nil),                // 1: dogfight.EntityData
	(*EntityData_AsteroidData)(nil),   // 2: dogfight.EntityData.AsteroidData
	(*EntityData_PlayerData)(nil),     // 3: dogfight.EntityData.PlayerData
	(*EntityData_PowerupData)(nil),    // 4: dogfight.EntityData.PowerupData
	(*EntityData_ProjectileData)(nil), // 5: dogfight.EntityData.ProjectileData
	(*Vector)(nil),                    // 6: dogfight.Vector
}
var file_entities_proto_depIdxs = []int32{
	0, // 0: dogfight.EntityData.type:type_name -> dogfight.EntityType
	6, // 1: dogfight.EntityData.position:type_name -> dogfight.Vector
	6, // 2: dogfight.EntityData.velocity:type_name -> dogfight.Vector
	2, // 3: dogfight.EntityData.asteroidData:type_name -> dogfight.EntityData.AsteroidData
	3, // 4: dogfight.EntityData.playerData:type_name -> dogfight.EntityData.PlayerData
	4, // 5: dogfight.EntityData.powerupData:type_name -> dogfight.EntityData.PowerupData
	5, // 6: dogfight.EntityData.projectileData:type_name -> dogfight.EntityData.ProjectileData
	6, // 7: dogfight.EntityData.AsteroidData.points:type_name -> dogfight.Vector
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_entities_proto_init() }
func file_entities_proto_init() {
	if File_entities_proto != nil {
		return
	}
	file_vector_proto_init()
	file_entities_proto_msgTypes[0].OneofWrappers = []any{
		(*EntityData_AsteroidData_)(nil),
		(*EntityData_PlayerData_)(nil),
		(*EntityData_PowerupData_)(nil),
		(*EntityData_ProjectileData_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_proto_rawDesc), len(file_entities_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_proto_goTypes,
		DependencyIndexes: file_entities_proto_depIdxs,
		EnumInfos:         file_entities_proto_enumTypes,
		MessageInfos:      file_entities_proto_msgTypes,
	}.Build()
	File_entities_proto = out.File
	file_entities_proto_goTypes = nil
	file_entities_proto_depIdxs = nil
}
