// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: entities.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityType int32

const (
	EntityType_ENTITY_TYPE_UNKNOWN    EntityType = 0
	EntityType_ENTITY_TYPE_ASTEROID   EntityType = 1
	EntityType_ENTITY_TYPE_PLAYER     EntityType = 2
	EntityType_ENTITY_TYPE_POWERUP    EntityType = 3
	EntityType_ENTITY_TYPE_PROJECTILE EntityType = 4
	EntityType_ENTITY_TYPE_MOCK       EntityType = 5
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_TYPE_UNKNOWN",
		1: "ENTITY_TYPE_ASTEROID",
		2: "ENTITY_TYPE_PLAYER",
		3: "ENTITY_TYPE_POWERUP",
		4: "ENTITY_TYPE_PROJECTILE",
		5: "ENTITY_TYPE_MOCK",
	}
	EntityType_value = map[string]int32{
		"ENTITY_TYPE_UNKNOWN":    0,
		"ENTITY_TYPE_ASTEROID":   1,
		"ENTITY_TYPE_PLAYER":     2,
		"ENTITY_TYPE_POWERUP":    3,
		"ENTITY_TYPE_PROJECTILE": 4,
		"ENTITY_TYPE_MOCK":       5,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_entities_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_entities_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{0}
}

type Entity struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Type     EntityType             `protobuf:"varint,1,opt,name=type,proto3,enum=game.EntityType" json:"type,omitempty"`
	Id       string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Position *Vector                `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Velocity *Vector                `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Rotation float64                `protobuf:"fixed64,5,opt,name=rotation,proto3" json:"rotation,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Entity_AsteroidData_
	//	*Entity_PlayerData_
	//	*Entity_PowerupData_
	//	*Entity_ProjectileData_
	Data          isEntity_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetType() EntityType {
	if x != nil {
		return x.Type
	}
	return EntityType_ENTITY_TYPE_UNKNOWN
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetPosition() *Vector {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Entity) GetVelocity() *Vector {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *Entity) GetRotation() float64 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *Entity) GetData() isEntity_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Entity) GetAsteroidData() *Entity_AsteroidData {
	if x != nil {
		if x, ok := x.Data.(*Entity_AsteroidData_); ok {
			return x.AsteroidData
		}
	}
	return nil
}

func (x *Entity) GetPlayerData() *Entity_PlayerData {
	if x != nil {
		if x, ok := x.Data.(*Entity_PlayerData_); ok {
			return x.PlayerData
		}
	}
	return nil
}

func (x *Entity) GetPowerupData() *Entity_PowerupData {
	if x != nil {
		if x, ok := x.Data.(*Entity_PowerupData_); ok {
			return x.PowerupData
		}
	}
	return nil
}

func (x *Entity) GetProjectileData() *Entity_ProjectileData {
	if x != nil {
		if x, ok := x.Data.(*Entity_ProjectileData_); ok {
			return x.ProjectileData
		}
	}
	return nil
}

type isEntity_Data interface {
	isEntity_Data()
}

type Entity_AsteroidData_ struct {
	AsteroidData *Entity_AsteroidData `protobuf:"bytes,6,opt,name=asteroidData,proto3,oneof"`
}

type Entity_PlayerData_ struct {
	PlayerData *Entity_PlayerData `protobuf:"bytes,7,opt,name=playerData,proto3,oneof"`
}

type Entity_PowerupData_ struct {
	PowerupData *Entity_PowerupData `protobuf:"bytes,8,opt,name=powerupData,proto3,oneof"`
}

type Entity_ProjectileData_ struct {
	ProjectileData *Entity_ProjectileData `protobuf:"bytes,9,opt,name=projectileData,proto3,oneof"`
}

func (*Entity_AsteroidData_) isEntity_Data() {}

func (*Entity_PlayerData_) isEntity_Data() {}

func (*Entity_PowerupData_) isEntity_Data() {}

func (*Entity_ProjectileData_) isEntity_Data() {}

type Entity_AsteroidData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Vector              `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity_AsteroidData) Reset() {
	*x = Entity_AsteroidData{}
	mi := &file_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity_AsteroidData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity_AsteroidData) ProtoMessage() {}

func (x *Entity_AsteroidData) ProtoReflect() protoreflect.Message {
	mi := &file_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity_AsteroidData.ProtoReflect.Descriptor instead.
func (*Entity_AsteroidData) Descriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Entity_AsteroidData) GetPoints() []*Vector {
	if x != nil {
		return x.Points
	}
	return nil
}

type Entity_PlayerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Score         uint32                 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Flags         uint32                 `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity_PlayerData) Reset() {
	*x = Entity_PlayerData{}
	mi := &file_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity_PlayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity_PlayerData) ProtoMessage() {}

func (x *Entity_PlayerData) ProtoReflect() protoreflect.Message {
	mi := &file_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity_PlayerData.ProtoReflect.Descriptor instead.
func (*Entity_PlayerData) Descriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Entity_PlayerData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Entity_PlayerData) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Entity_PlayerData) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type Entity_PowerupData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ability       uint32                 `protobuf:"varint,1,opt,name=ability,proto3" json:"ability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity_PowerupData) Reset() {
	*x = Entity_PowerupData{}
	mi := &file_entities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity_PowerupData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity_PowerupData) ProtoMessage() {}

func (x *Entity_PowerupData) ProtoReflect() protoreflect.Message {
	mi := &file_entities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity_PowerupData.ProtoReflect.Descriptor instead.
func (*Entity_PowerupData) Descriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Entity_PowerupData) GetAbility() uint32 {
	if x != nil {
		return x.Ability
	}
	return 0
}

type Entity_ProjectileData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         uint32                 `protobuf:"varint,1,opt,name=flags,proto3" json:"flags,omitempty"`
	Lifetime      int32                  `protobuf:"varint,2,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity_ProjectileData) Reset() {
	*x = Entity_ProjectileData{}
	mi := &file_entities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity_ProjectileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity_ProjectileData) ProtoMessage() {}

func (x *Entity_ProjectileData) ProtoReflect() protoreflect.Message {
	mi := &file_entities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity_ProjectileData.ProtoReflect.Descriptor instead.
func (*Entity_ProjectileData) Descriptor() ([]byte, []int) {
	return file_entities_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Entity_ProjectileData) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Entity_ProjectileData) GetLifetime() int32 {
	if x != nil {
		return x.Lifetime
	}
	return 0
}

var File_entities_proto protoreflect.FileDescriptor

const file_entities_proto_rawDesc = "" +
	"\n" +
	"\x0eentities.proto\x12\x04game\x1a\fvector.proto\"\xb0\x05\n" +
	"\x06Entity\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.game.EntityTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12(\n" +
	"\bposition\x18\x03 \x01(\v2\f.game.VectorR\bposition\x12(\n" +
	"\bvelocity\x18\x04 \x01(\v2\f.game.VectorR\bvelocity\x12\x1a\n" +
	"\brotation\x18\x05 \x01(\x01R\brotation\x12?\n" +
	"\fasteroidData\x18\x06 \x01(\v2\x19.game.Entity.AsteroidDataH\x00R\fasteroidData\x129\n" +
	"\n" +
	"playerData\x18\a \x01(\v2\x17.game.Entity.PlayerDataH\x00R\n" +
	"playerData\x12<\n" +
	"\vpowerupData\x18\b \x01(\v2\x18.game.Entity.PowerupDataH\x00R\vpowerupData\x12E\n" +
	"\x0eprojectileData\x18\t \x01(\v2\x1b.game.Entity.ProjectileDataH\x00R\x0eprojectileData\x1a4\n" +
	"\fAsteroidData\x12$\n" +
	"\x06points\x18\x01 \x03(\v2\f.game.VectorR\x06points\x1aT\n" +
	"\n" +
	"PlayerData\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05score\x18\x02 \x01(\rR\x05score\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\rR\x05flags\x1a'\n" +
	"\vPowerupData\x12\x18\n" +
	"\aability\x18\x01 \x01(\rR\aability\x1aB\n" +
	"\x0eProjectileData\x12\x14\n" +
	"\x05flags\x18\x01 \x01(\rR\x05flags\x12\x1a\n" +
	"\blifetime\x18\x02 \x01(\x05R\blifetimeB\x06\n" +
	"\x04data*\xa2\x01\n" +
	"\n" +
	"EntityType\x12\x17\n" +
	"\x13ENTITY_TYPE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14ENTITY_TYPE_ASTEROID\x10\x01\x12\x16\n" +
	"\x12ENTITY_TYPE_PLAYER\x10\x02\x12\x17\n" +
	"\x13ENTITY_TYPE_POWERUP\x10\x03\x12\x1a\n" +
	"\x16ENTITY_TYPE_PROJECTILE\x10\x04\x12\x14\n" +
	"\x10ENTITY_TYPE_MOCK\x10\x05B\x05Z\x03/pbb\x06proto3"

var (
	file_entities_proto_rawDescOnce sync.Once
	file_entities_proto_rawDescData []byte
)

func file_entities_proto_rawDescGZIP() []byte {
	file_entities_proto_rawDescOnce.Do(func() {
		file_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_proto_rawDesc), len(file_entities_proto_rawDesc)))
	})
	return file_entities_proto_rawDescData
}

var file_entities_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_entities_proto_goTypes = []any{
	(EntityType)(0),               // 0: game.EntityType
	(*Entity)(nil),                // 1: game.Entity
	(*Entity_AsteroidData)(nil),   // 2: game.Entity.AsteroidData
	(*Entity_PlayerData)(nil),     // 3: game.Entity.PlayerData
	(*Entity_PowerupData)(nil),    // 4: game.Entity.PowerupData
	(*Entity_ProjectileData)(nil), // 5: game.Entity.ProjectileData
	(*Vector)(nil),                // 6: game.Vector
}
var file_entities_proto_depIdxs = []int32{
	0, // 0: game.Entity.type:type_name -> game.EntityType
	6, // 1: game.Entity.position:type_name -> game.Vector
	6, // 2: game.Entity.velocity:type_name -> game.Vector
	2, // 3: game.Entity.asteroidData:type_name -> game.Entity.AsteroidData
	3, // 4: game.Entity.playerData:type_name -> game.Entity.PlayerData
	4, // 5: game.Entity.powerupData:type_name -> game.Entity.PowerupData
	5, // 6: game.Entity.projectileData:type_name -> game.Entity.ProjectileData
	6, // 7: game.Entity.AsteroidData.points:type_name -> game.Vector
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_entities_proto_init() }
func file_entities_proto_init() {
	if File_entities_proto != nil {
		return
	}
	file_vector_proto_init()
	file_entities_proto_msgTypes[0].OneofWrappers = []any{
		(*Entity_AsteroidData_)(nil),
		(*Entity_PlayerData_)(nil),
		(*Entity_PowerupData_)(nil),
		(*Entity_ProjectileData_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_proto_rawDesc), len(file_entities_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_proto_goTypes,
		DependencyIndexes: file_entities_proto_depIdxs,
		EnumInfos:         file_entities_proto_enumTypes,
		MessageInfos:      file_entities_proto_msgTypes,
	}.Build()
	File_entities_proto = out.File
	file_entities_proto_goTypes = nil
	file_entities_proto_depIdxs = nil
}
