// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: event.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNKNOWN  EventType = 0
	EventType_EVENT_TYPE_JOIN     EventType = 1
	EventType_EVENT_TYPE_QUIT     EventType = 2
	EventType_EVENT_TYPE_RESPAWN  EventType = 3
	EventType_EVENT_TYPE_INPUT    EventType = 4
	EventType_EVENT_TYPE_SNAPSHOT EventType = 5
	EventType_EVENT_TYPE_DELTA    EventType = 6
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNKNOWN",
		1: "EVENT_TYPE_JOIN",
		2: "EVENT_TYPE_QUIT",
		3: "EVENT_TYPE_RESPAWN",
		4: "EVENT_TYPE_INPUT",
		5: "EVENT_TYPE_SNAPSHOT",
		6: "EVENT_TYPE_DELTA",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNKNOWN":  0,
		"EVENT_TYPE_JOIN":     1,
		"EVENT_TYPE_QUIT":     2,
		"EVENT_TYPE_RESPAWN":  3,
		"EVENT_TYPE_INPUT":    4,
		"EVENT_TYPE_SNAPSHOT": 5,
		"EVENT_TYPE_DELTA":    6,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=dogfight.EventType" json:"type,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Event_JoinEventData_
	//	*Event_QuitEventData_
	//	*Event_RespawnEventData_
	//	*Event_InputEventData_
	//	*Event_SnapshotEventData_
	//	*Event_DeltaEventData_
	Data          isEvent_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNKNOWN
}

func (x *Event) GetData() isEvent_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetJoinEventData() *Event_JoinEventData {
	if x != nil {
		if x, ok := x.Data.(*Event_JoinEventData_); ok {
			return x.JoinEventData
		}
	}
	return nil
}

func (x *Event) GetQuitEventData() *Event_QuitEventData {
	if x != nil {
		if x, ok := x.Data.(*Event_QuitEventData_); ok {
			return x.QuitEventData
		}
	}
	return nil
}

func (x *Event) GetRespawnEventData() *Event_RespawnEventData {
	if x != nil {
		if x, ok := x.Data.(*Event_RespawnEventData_); ok {
			return x.RespawnEventData
		}
	}
	return nil
}

func (x *Event) GetInputEventData() *Event_InputEventData {
	if x != nil {
		if x, ok := x.Data.(*Event_InputEventData_); ok {
			return x.InputEventData
		}
	}
	return nil
}

func (x *Event) GetSnapshotEventData() *Event_SnapshotEventData {
	if x != nil {
		if x, ok := x.Data.(*Event_SnapshotEventData_); ok {
			return x.SnapshotEventData
		}
	}
	return nil
}

func (x *Event) GetDeltaEventData() *Event_DeltaEventData {
	if x != nil {
		if x, ok := x.Data.(*Event_DeltaEventData_); ok {
			return x.DeltaEventData
		}
	}
	return nil
}

type isEvent_Data interface {
	isEvent_Data()
}

type Event_JoinEventData_ struct {
	JoinEventData *Event_JoinEventData `protobuf:"bytes,2,opt,name=joinEventData,proto3,oneof"`
}

type Event_QuitEventData_ struct {
	QuitEventData *Event_QuitEventData `protobuf:"bytes,3,opt,name=quitEventData,proto3,oneof"`
}

type Event_RespawnEventData_ struct {
	RespawnEventData *Event_RespawnEventData `protobuf:"bytes,4,opt,name=respawnEventData,proto3,oneof"`
}

type Event_InputEventData_ struct {
	InputEventData *Event_InputEventData `protobuf:"bytes,5,opt,name=inputEventData,proto3,oneof"`
}

type Event_SnapshotEventData_ struct {
	SnapshotEventData *Event_SnapshotEventData `protobuf:"bytes,6,opt,name=snapshotEventData,proto3,oneof"`
}

type Event_DeltaEventData_ struct {
	DeltaEventData *Event_DeltaEventData `protobuf:"bytes,7,opt,name=deltaEventData,proto3,oneof"`
}

func (*Event_JoinEventData_) isEvent_Data() {}

func (*Event_QuitEventData_) isEvent_Data() {}

func (*Event_RespawnEventData_) isEvent_Data() {}

func (*Event_InputEventData_) isEvent_Data() {}

func (*Event_SnapshotEventData_) isEvent_Data() {}

func (*Event_DeltaEventData_) isEvent_Data() {}

type Event_JoinEventData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_JoinEventData) Reset() {
	*x = Event_JoinEventData{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_JoinEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_JoinEventData) ProtoMessage() {}

func (x *Event_JoinEventData) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_JoinEventData.ProtoReflect.Descriptor instead.
func (*Event_JoinEventData) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Event_JoinEventData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event_JoinEventData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Event_QuitEventData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_QuitEventData) Reset() {
	*x = Event_QuitEventData{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_QuitEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_QuitEventData) ProtoMessage() {}

func (x *Event_QuitEventData) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_QuitEventData.ProtoReflect.Descriptor instead.
func (*Event_QuitEventData) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Event_QuitEventData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Event_RespawnEventData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_RespawnEventData) Reset() {
	*x = Event_RespawnEventData{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_RespawnEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_RespawnEventData) ProtoMessage() {}

func (x *Event_RespawnEventData) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_RespawnEventData.ProtoReflect.Descriptor instead.
func (*Event_RespawnEventData) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Event_RespawnEventData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Event_InputEventData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MouseX        float64                `protobuf:"fixed64,2,opt,name=mouseX,proto3" json:"mouseX,omitempty"`
	MouseY        float64                `protobuf:"fixed64,3,opt,name=mouseY,proto3" json:"mouseY,omitempty"`
	MousePressed  bool                   `protobuf:"varint,4,opt,name=mousePressed,proto3" json:"mousePressed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_InputEventData) Reset() {
	*x = Event_InputEventData{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_InputEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_InputEventData) ProtoMessage() {}

func (x *Event_InputEventData) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_InputEventData.ProtoReflect.Descriptor instead.
func (*Event_InputEventData) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Event_InputEventData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event_InputEventData) GetMouseX() float64 {
	if x != nil {
		return x.MouseX
	}
	return 0
}

func (x *Event_InputEventData) GetMouseY() float64 {
	if x != nil {
		return x.MouseY
	}
	return 0
}

func (x *Event_InputEventData) GetMousePressed() bool {
	if x != nil {
		return x.MousePressed
	}
	return false
}

type Event_SnapshotEventData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int32                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Entities      []*EntityData          `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_SnapshotEventData) Reset() {
	*x = Event_SnapshotEventData{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_SnapshotEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_SnapshotEventData) ProtoMessage() {}

func (x *Event_SnapshotEventData) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_SnapshotEventData.ProtoReflect.Descriptor instead.
func (*Event_SnapshotEventData) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Event_SnapshotEventData) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event_SnapshotEventData) GetEntities() []*EntityData {
	if x != nil {
		return x.Entities
	}
	return nil
}

type Event_DeltaEventData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int32                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Updated       []*EntityData          `protobuf:"bytes,2,rep,name=updated,proto3" json:"updated,omitempty"`
	Removed       []string               `protobuf:"bytes,3,rep,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_DeltaEventData) Reset() {
	*x = Event_DeltaEventData{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_DeltaEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_DeltaEventData) ProtoMessage() {}

func (x *Event_DeltaEventData) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_DeltaEventData.ProtoReflect.Descriptor instead.
func (*Event_DeltaEventData) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Event_DeltaEventData) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event_DeltaEventData) GetUpdated() []*EntityData {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *Event_DeltaEventData) GetRemoved() []string {
	if x != nil {
		return x.Removed
	}
	return nil
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\bdogfight\x1a\x0eentities.proto\"\xd4\a\n" +
	"\x05Event\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.dogfight.EventTypeR\x04type\x12E\n" +
	"\rjoinEventData\x18\x02 \x01(\v2\x1d.dogfight.Event.JoinEventDataH\x00R\rjoinEventData\x12E\n" +
	"\rquitEventData\x18\x03 \x01(\v2\x1d.dogfight.Event.QuitEventDataH\x00R\rquitEventData\x12N\n" +
	"\x10respawnEventData\x18\x04 \x01(\v2 .dogfight.Event.RespawnEventDataH\x00R\x10respawnEventData\x12H\n" +
	"\x0einputEventData\x18\x05 \x01(\v2\x1e.dogfight.Event.InputEventDataH\x00R\x0einputEventData\x12Q\n" +
	"\x11snapshotEventData\x18\x06 \x01(\v2!.dogfight.Event.SnapshotEventDataH\x00R\x11snapshotEventData\x12H\n" +
	"\x0edeltaEventData\x18\a \x01(\v2\x1e.dogfight.Event.DeltaEventDataH\x00R\x0edeltaEventData\x1a;\n" +
	"\rJoinEventData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x1a\x1f\n" +
	"\rQuitEventData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x1a\"\n" +
	"\x10RespawnEventData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x1at\n" +
	"\x0eInputEventData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06mouseX\x18\x02 \x01(\x01R\x06mouseX\x12\x16\n" +
	"\x06mouseY\x18\x03 \x01(\x01R\x06mouseY\x12\"\n" +
	"\fmousePressed\x18\x04 \x01(\bR\fmousePressed\x1ac\n" +
	"\x11SnapshotEventData\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x05R\ttimestamp\x120\n" +
	"\bentities\x18\x02 \x03(\v2\x14.dogfight.EntityDataR\bentities\x1ax\n" +
	"\x0eDeltaEventData\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x05R\ttimestamp\x12.\n" +
	"\aupdated\x18\x02 \x03(\v2\x14.dogfight.EntityDataR\aupdated\x12\x18\n" +
	"\aremoved\x18\x03 \x03(\tR\aremovedB\x06\n" +
	"\x04data*\xaa\x01\n" +
	"\tEventType\x12\x16\n" +
	"\x12EVENT_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fEVENT_TYPE_JOIN\x10\x01\x12\x13\n" +
	"\x0fEVENT_TYPE_QUIT\x10\x02\x12\x16\n" +
	"\x12EVENT_TYPE_RESPAWN\x10\x03\x12\x14\n" +
	"\x10EVENT_TYPE_INPUT\x10\x04\x12\x17\n" +
	"\x13EVENT_TYPE_SNAPSHOT\x10\x05\x12\x14\n" +
	"\x10EVENT_TYPE_DELTA\x10\x06B\x05Z\x03/pbb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_event_proto_goTypes = []any{
	(EventType)(0),                  // 0: dogfight.EventType
	(*Event)(nil),                   // 1: dogfight.Event
	(*Event_JoinEventData)(nil),     // 2: dogfight.Event.JoinEventData
	(*Event_QuitEventData)(nil),     // 3: dogfight.Event.QuitEventData
	(*Event_RespawnEventData)(nil),  // 4: dogfight.Event.RespawnEventData
	(*Event_InputEventData)(nil),    // 5: dogfight.Event.InputEventData
	(*Event_SnapshotEventData)(nil), // 6: dogfight.Event.SnapshotEventData
	(*Event_DeltaEventData)(nil),    // 7: dogfight.Event.DeltaEventData
	(*EntityData)(nil),              // 8: dogfight.EntityData
}
var file_event_proto_depIdxs = []int32{
	0, // 0: dogfight.Event.type:type_name -> dogfight.EventType
	2, // 1: dogfight.Event.joinEventData:type_name -> dogfight.Event.JoinEventData
	3, // 2: dogfight.Event.quitEventData:type_name -> dogfight.Event.QuitEventData
	4, // 3: dogfight.Event.respawnEventData:type_name -> dogfight.Event.RespawnEventData
	5, // 4: dogfight.Event.inputEventData:type_name -> dogfight.Event.InputEventData
	6, // 5: dogfight.Event.snapshotEventData:type_name -> dogfight.Event.SnapshotEventData
	7, // 6: dogfight.Event.deltaEventData:type_name -> dogfight.Event.DeltaEventData
	8, // 7: dogfight.Event.SnapshotEventData.entities:type_name -> dogfight.EntityData
	8, // 8: dogfight.Event.DeltaEventData.updated:type_name -> dogfight.EntityData
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_entities_proto_init()
	file_event_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_JoinEventData_)(nil),
		(*Event_QuitEventData_)(nil),
		(*Event_RespawnEventData_)(nil),
		(*Event_InputEventData_)(nil),
		(*Event_SnapshotEventData_)(nil),
		(*Event_DeltaEventData_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
